# Define the sequence for 6klg
sequence_6klg = "TIYARKDDVVIVNVYNQGYKNITLHWHGVDQPRNPWSDGPEYITQCPIQPGANFTYKIIF" \
                "TEEEGTLWWHAHSEFDRATVHGAIVIHPKRGTVYPYPKPHKEMPIILGEWWNADVEQILL" \
                "ESQRTGGDVNISDANTINGQPGDFAPCSKEDTFKMSVEHGKTYLLRVINAGLTNEMFFAV" \
                "AGHRLTVVGTDGRYLRPFTVDYILISPGQTMNMLLEANCATDGSANSRYYMAARPFFTNT" \
                "AVNVDDKNTTAIVEYTDAPPSAS-----AGPPDSPDLPAMDDIAAATAYTAQLRSLVTKE" \
                "HPIDVPMEVDEHMLVTISVNTIPCEPNKTCAGPGNNRLAASLNNVSFMNPTIDILDAYYD" \
                "SISG-VYEPDFPNKPPFFFNFTAPNPPQDLWFTKRGTKVKVVEYGTILEVVFQDTAILGA" \
                "ESHPMHLHGFSFYVVGRGFGNFDKDKDPATYNLVDPPYQNTVSVPTGGWAAMRFRAANPG" \
                "VWFMHCHFDRHTVWGMDTVFIVKNGKGPDAQMMPRPPNMPKC"

# Define the range of residues to keep (e.g., from residue 113 to 526)
start_position = 113
end_position = 526

# Extract the specified region
specific_region_6klg = sequence_6klg[start_position - 1:end_position]

# Print or process the specified region
print(specific_region_6klg)